CREATE DATABASE IF NOT EXISTS btc;

USE btc;

CREATE TABLE IF NOT EXISTS btc_prices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
