
# GET http://localhost:3000/api/inventory-storage-unit/inventories-by-storageunit?storageunit_id=1
# http://localhost:3000/api/inventories-by-storageunit/1
# http://localhost:3000/api/inventory-storage-unit/inventories-by-storageunit/1/inventories`
# GET http://localhost:3000/api/storageUnits/1/inventories
    # GET http://localhost:3000/api/storageUnits/1/inventories
# get http://localhost:3000/api/Chemequipments/equipments?category=general


# GET http://localhost:3000/api/Chemequipments/equipments?category=general

# GET http://localhost:3000/api/chemEquipments/groups?category=general




# GET http://localhost:3000/api/Chemequipments/equipments?category=specialized&group=Stirring+Equipment


# GET http://localhost:3000/api/ChemEquipments/equipments?category=specialized&group=Storage%20Equipment



# GET http://localhost:3000/api/inventoryStorageUnit/15/inventories-with-location

# GET http://localhost:3000/api/inventoryStorageUnit/15/inventories

# get http://localhost:3000/api/chemEquipments/2/locations

# GET http://localhost:3000/api/inventoryStorageUnit/1/inventories


# GET http://localhost:3000/api/inventories/filter?reference_id=1&item_type=element

# GET http://localhost:3000/api/inventories/filter?reference_id=3&item_type=compound

# GET http://localhost:3000/api/inventories/

        # GET http://localhost:3000/api/storageunits/15/location-chain



# GET http://localhost:3000/api/inventories/locations/equipment/1

# put http://localhost:3000/api/inventories/1`, { status:  });

# put http://localhost:3000/api/inventories/1

        # POST http://localhost:3000/api/users/login
        # Content-Type: application/json

        # {
        #   "email": "georgiigiblov@gmail.com",
        #   "password": "1234"
        # }

        # # GET http://localhost:3000/api/users/profile
        # # Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJnZW9yZ2lpZ2libG92QGdtYWlsLmNvbSIsImlhdCI6MTczNjM1ODg1NywiZXhwIjoxNzM2MzYyNDU3fQ.DxzyNqIvWN0REPaxCKtzurzzy2ZXvU11z1wd1M8tyvE


        # POST http://localhost:3000/api/carts
        # Content-Type: application/json

        # {
        # "user_id": 1,
        # "item_id": 14,
        # "item_name": "Test Item",
        # "quantity": 2
        # }

        
        # GET http://localhost:3000/api/taskFiles/research/1

        # GET http://localhost:3000/api/tasks/research?researchId=1

        # get http://localhost:3000/api/inventories

        # get http://localhost:3000/api/inventories/chemicals/count

        # get http://localhost:3000/api/researches/ongoing/count

# get http://localhost:3000/api/orders/active/count

get http://localhost:3000/api/logs